import type { Metadata } from "next";
import { Inter, Noto_Sans_Myanmar } from "next/font/google";
import "./globals.css";

import NavbarProvider from "@/components/ui/Navbar/NavbarProvider";
import { ConvexClientProvider } from "./ConvexClientProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const myanmar = Noto_Sans_Myanmar({
  subsets: ["myanmar"],
  variable: "--font-myanmar",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-display bg-(--color-bg-light) dark:bg-(--color-bg-dark) text-white ${inter.variable} ${myanmar.variable}`}>
        <ConvexClientProvider>
          <NavbarProvider />
          {children}
        </ConvexClientProvider>
      </body>
    </html>
  );
}
